-- Create procedure and function using SQLPlus

SELECT * FROM EMP WHERE COMM IS NULL;

SELECT * FROM EMP WHERE COMM IS NOT NULL;

INSERT INTO EMP (EMPNO,ENAME,JOB,COMM,DEPTNO)
VALUES (5672,'TIBYAN','IT',NULL,10);

INSERT INTO EMP (EMPNO,ENAME,JOB,COMM,DEPTNO)
VALUES (5673,'AHMED','IT','',20);

INSERT INTO EMP (EMPNO,ENAME,JOB,COMM,DEPTNO)
VALUES (5674,'SALIM','SALESMAN',0,20);

CREATE OR REPLACE PROCEDURE TIBYAN_PR_TEST IS
BEGIN
   DBMS_OUTPUT.PUT_LINE('WELCOME TO ORACLE EBS PROC....!!!!');
END;
/

SET SERVEROUTPUT ON;

EXEC TIBYAN_PR_TEST;

BEGIN
  TIBYAN_PR_TEST;
  RAZAN_PR_TEST;
  MARIYA_PR_TEST;
END;
/

CREATE OR REPLACE FUNCTION TIBYAN_FN_TEST RETURN VARCHAR2 IS
V_MSG VARCHAR2(2000);
BEGIN
    V_MSG :='WELCOME TO ORACLE EBS FN!!!';
RETURN V_MSG;
END;
/

SELECT TIBYAN_FN_TEST FROM DUAL;

DECLARE
X VARCHAR2(2000);
BEGIN
   TIBYAN_PR_TEST;
   X:= TIBYAN_FN_TEST;
   DBMS_OUTPUT.PUT_LINE(X);
END;
/